export const routes = {
  home: "/home",
  products: "/products",
  productList: "/products/list",
  productDetail: "/products/classic-burger",
  cart: "/cart",
  checkout: "/checkout",
  wishlist: "/wishlist",
  contact: "/contact",
  faqs: "/faqs",
  login: "/login",
  register: "/register",
  recoverPassword: "/recover-password",
  resetPassword: "/reset-password",
  admin: {
    dashboard: "/admin/dashboard",
    manage: "/admin/manage",
    orders: "/admin/orders",
    orderDetails: "/admin/orders/1",
    customers: "/admin/customers",
    restaurants: "/admin/restaurants",
    products: "/admin/products",
    sellers: "/admin/sellers",
    wallet: "/admin/wallet",
    settings: "/admin/settings",
  },
} as const;
